[pytest]
pythonpath = . experiments
testpaths =
    tests
    fastridge.py
    experiments/data.py
    experiments/problems.py
    experiments/experiments.py
    README.md
    experiments/double_asymptotic_trends.ipynb
    experiments/sparse_designs.ipynb
    experiments/tutorial.ipynb
    experiments/real_data.ipynb
    experiments/timing_analysis.ipynb
addopts =
    --doctest-modules
    --codeblocks
    --nbmake
