name: Tests

on:
  push:
    branches:
      - dev
      - main

jobs:
  package-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install .
      - run: pip install pytest
      - run: pytest --doctest-modules fastridge.py

  project-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: pip install .
      - run: pytest
